### ISSUE TITLE
PSAT naming conventions

### ISSUE THREAD

**Issue by wbuchanan** [rowen0718/SQL-Queries#20]
The previously agreed upon naming convention scheme is:

`testCode + subjectCode + scoreCode [ + # ]`

Where `testCode` is a three character string that identifies the assessment: 

testCode | Meaning
--------- | ---------
kpr | K-Prep
act | ACT
psa | PSAT
map | NWEA MAP
brg | Brigance
acc | ACCESS
cog | CogAT
ibs | Iowa Test of Basic Skills
kos | KOSSA
kyt | KYOTTE

__AND__

Where `subjectCode` is a three character string that identifies the major subject area

subjectCode | Meaning
--------- | ---------
rla | Reading/Language Arts
mth | Mathematics
sci | Science
his | History
wrt | Writing

Some assessments use more detailed subject area descriptors and those subject areas can be identified and documented to reserve the character sequence

__AND__

Where `scoreCode` is a two or three character string identifying the metric type

scoreCode | Meaning
--------- | ---------
sc | Scaled score
raw | Raw score
lev | Performance level (e.g., 1 = Novice, 2 = Apprentice, 3 = Proficient, & 4 = Distinguished)
pct | Percentiles
dec | Deciles
sgp | Student Growth Percentiles
prj | Projected Growth
grw | Observed Growth
gle | Grade Level equivalents

__AND__

Optionally a number that indicates a within year period for assessments with regular testing intervals within a year (e.g., 1 = Fall, 2 = Winter, 3 = Spring, etc...).  In this case the number only has meaning in the context of the assessment referenced but should indicate the order of the testing window from which the score was derived.

**Comment by wbuchanan** [comment]
@rowen0718 Has this been fixed yet?

**Comment by rowen0718** [comment]
I went back through and updated the language in the PSAT query to reflect this language. It is now consistent with the others.



Sent from my T-Mobile 4G LTE Device


-------- Original message --------
