### ISSUE TITLE
Brigance Naming Conventions

### ISSUE THREAD

**Issue by wbuchanan** [rowen0718/SQL-Queries#26]
See [Naming Conventions](https://github.com/wbuchanan/fcps-standards/blob/gh-pages/_includes/naming.md) for additional info.

**Comment by rowen0718** [comment]
What naming conventions do we want to use for Physical Well-Being, Language/Communication, Adaptive Behavior, and Self-Help Skills Performance?

**Comment by wbuchanan** [comment]
Propose something.  As long as it conforms to the other conventions (e.g., 3 characters for subject area/scale) and is unique to the scale it should be fine.  But make sure that you submit an issue for the naming convention update and modify the table in the file referenced above.

**Comment by rowen0718** [comment]
Naming conventions have been updated in the script and new ones have been proposed to cover those that were unique to Brigance
